Update description
mate-academy/kt-library-service pull request #6
Opened 2024-04-08 05:56 UTC by pavlosoletskyy

2024-04-08 12:03 UTC, alenatovstukha requested changes

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
> +##Instructions
space between ## and Instructions

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
>     - `title` of type `String`
- `title` of type `String`;

semicolon `;`

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
>     - `authors` of type `List<Author>`
`;`

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
>     - `publicationYear` of type `Int`
`;`

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
>     - `genre` of type `String`
`;`

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
>     - `isbn` of type `String`
`;`

2024-04-08 12:03 UTC, alenatovstukha commented on README.md
> +💡**HINT:** use some collection here. Book duplicates are allowed.
💡 Use some collection here. Book duplicates are allowed.

2024-04-09 08:51 UTC, boroda4436 approved these changes

2024-04-09 08:51 UTC, merged